server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: provider
      path: /zuul/**
  ignored-services: provider
#  ignored-services: "*"
  prefix: /xiaosama

#  AccessTokenFilter:
#    pre:
#      disable: true
#  AccessTokenFilter1:
#    pre:
#      disable: true